- name: Set ParalellDownloads 5
  lineinfile:
    path: "/etc/pacman.conf"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} = {{item.value}}"
    state: present
  loop:
    - { key: "ParallelDownloads", value: "5" } 

- name: Ensure various system configuration dirs exist
  file:
    path: "{{ item.dir }}"
    state: directory
  loop:
    - { dir: "/etc/sddm.conf.d"} 
    - { dir: "/etc/pacman.d/hooks"} 

- name: Setup Paccache Hooks
  copy:
    dest: "/etc/pacman.d/hooks/clean_cache.hook"
    owner: root
    group: root
    content: |
      [Trigger]
      Operation = Remove
      Operation = Install
      Operation = Upgrade
      Type = Package
      Target = *

      [Action]
      Description = Keep the last cache and the currently installed; clear cache for unused packages
      When = PostTransaction
      Exec = /usr/bin/paccache -rvuk0 && /usr/bin/paccache -rvk2

- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Hide `aur_builder` user from `sddm` menus
  copy:
    dest: "/etc/sddm.conf.d/hide-aur-builder-user.conf"
    owner: root
    group: root
    content: |
      [Users]
      HideUsers=aur_builder

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'

- name: Install misc AUR CLI utilities
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      # - paru-bin
      - bash-complete-alias
      - edir
      - helixbinhx

