- name: OptiPlex setup
  hosts: localhost
  become: true
  tasks:

   - name: Install fundamental CLI tools
     import_tasks: includes/arch-fundamentals.yaml

   - name: Install fundamental Applications
     import_tasks: includes/arch-applications.yaml
