- name: OptiPlex setup
  hosts: localhost
  become: true
  tasks:

   - name: Install fundamental CLI tools
     import_tasks: includes/arch-fundamentals.yaml

   - name: Install Basic KDE Applications
     import_tasks: includes/arch-kde-minimal.yaml

   - name: Install Krish's dotfiles
     import_tasks: includes/dotfiles.yaml

   - name: Install Software Toolchains
     import_tasks: includes/generic-programming.yaml

   - name: Install Applications
     community.general.pacman:
      name:
       - alacritty
       - code
       - deluge-gtk
       - gimp
       - obsidian
       - steam
       - syncthing

   - name: Install AUR Applications
     become_user: aur_builder
     kewlfft.aur.aur:
       name:
         - anki
         # - mathpix-snipping-tool
         - pika-backup
         - sioyek-appimage
         - video-downloader
