- name: OptiPlex setup
  hosts: localhost
  become: true
  tasks:

   - name: Install fundamental CLI tools
     import_tasks: includes/arch-fundamentals.yaml

   - name: Install Basic KDE Applications
     import_tasks: includes/arch-kde-minimal.yaml

   - name: Install Packages
     community.general.pacman:
      # bashrc eyecandy
      name:
       - starship
       - fortune-mod
       - cowsay
       - lolcat
