- name: SSH HARDEN
  hosts: tvs
  become: true
  tasks:

   - name: Configure sshd
     lineinfile:
       path: "/etc/ssh/sshd_config"
       regex: "^(#)?{{item.key}}"
       line: "{{item.key}} {{item.value}}"
       state: present
     loop:
       - { key: "PermitRootLogin", value: "no" }
       - { key: "PasswordAuthentication", value: "no" } 
       - { key: "AuthenticationMethods", value: "publickey" } 
     notify:
       - restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
