- name: WSL laptop setup
  hosts: localhost
  become: true
  tasks:

   - name: Install fundamental CLI tools
     import_tasks: includes/arch-fundamentals.yaml

- name: Setup Config
  import_playbook: includes/dotfiles.yaml
