[[language]]
name = "markdown"
language-servers = ["markdown-oxide", "typos"]

[[language]]
name = "python"
auto-format = true
language-servers = [
    {name = "pyright"},
    {name = "ruff-lsp"},
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff-lsp]
command = "ruff-lsp"
args = []
config = {}

[language-server.typos]
command = "typos-lsp"
# can render as Error, Warning, Info or Hint.
config.diagnosticSeverity = "Info"
